use customer_behavior;
Select * from customer;
desc customer;

-- Q1. What is the total revenue generated by male vs. female customers? --
select gender, SUM(purchase_amount) as Total_revenue from customer group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? --

Select customer_id, discount_applied, purchase_amount from customer 
where discount_applied ="Yes" and purchase_amount >= (SELECT AVG(purchase_amount)
    FROM customer);
    
-- Q3. Which are the top 5 products with the highest average review rating? --
Select item_purchased, AVG(review_rating)as Avg_Rev_Rating from customer 
group by item_purchased order by Avg_Rev_Rating limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, AVG(purchase_amount) AS avg_purchase_amount FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

use customer_behavior;

-- Q5. Do subscribed customers spend more? 
-- Compare average spend and total revenue between subscribers and non-subscribers.
Select subscription_status, AVG(purchase_amount) as average_spent, SUM(purchase_amount)as total_revenue 
from customer
GROUP BY subscription_status
order by subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND(
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 
        / COUNT(*),
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

SELECT 
    customer_segment,
    COUNT(*) AS customer_count
FROM (
    SELECT 
        customer_id,
        CASE 
            WHEN previous_purchases <= 5 THEN 'New'
            WHEN previous_purchases BETWEEN 6 AND 15 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
) AS segmented_customers
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category? --
WITH product_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchases
    FROM customer
    GROUP BY category, item_purchased
),

ranked_products AS (
    SELECT *,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY total_purchases DESC
        ) AS product_rank
    FROM product_counts
)

SELECT 
    category,
    item_purchased,
    total_purchases
FROM ranked_products
WHERE product_rank <= 3
ORDER BY category, product_rank;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    subscription_status,
    COUNT(*) AS customer_count,
    ROUND(
        COUNT(*) * 100.0 / 
        (SELECT COUNT(*) 
         FROM customer 
         WHERE previous_purchases > 5),
        2
    ) AS percentage
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;














